### ISSUE TITLE
[Bug Report]: System.InvalidOperationException: There is no offsets in the received queue. Call Enqueue first

### ISSUE THREAD

**Issue by vypsim** [Farfetch/kafkaflow#488]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

Hi,

I started seeing the following error from multiple services on ~~startup~~ restart since upgrading to kafkaflow v3

```
System.InvalidOperationException: There is no offsets in the received queue. Call Enqueue first
   at KafkaFlow.Consumers.PartitionOffsets.TryDequeue(IConsumerContext context)
   at KafkaFlow.Consumers.OffsetManager.MarkAsProcessed(IConsumerContext context)
   at KafkaFlow.Consumers.ConsumerContext.Complete()
   at KafkaFlow.Consumers.ConsumerWorker.ProcessMessageAsync(IMessageContext context, CancellationToken cancellationToken)
```

It happens on services that don't necessarily use batching or have `WithoutStoringOffsets`, just standard consumers.
And I haven't been able to replicate it locally, only on the cloud.

### Steps to reproduce

Upgrade to kafkaflow 3.0
Deploy services

### Expected behavior

Exception not thrown

### Actual behavior

Exception is thrown

### KafkaFlow version

3.0.0

**Comment by vypsim** [comment]
Thanks for fixing the issue.
